apiVersion: example.com/v1
kind: MyApp
metadata: # kpt-merge: example1/test-app
  name: test-app
  namespace: example1
  annotations:
    internal.kpt.dev/upstream-identifier: 'example.com|MyApp|example1|test-app'
spec:
  replicas: 3
  environment: dev
  version: release-1.0.0
  language: golang
