apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: helmrepo
  namespace: default
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: helmrepo
      version: '1.0.4'
      sourceRef:
        kind: HelmRepository
        name: helmrepo
      interval: 5m
  releaseName: helmrepo
  targetNamespace: default 
  valuesFrom:
  - kind: ConfigMap
    name: helmrepo-values
    valuesKey: values.yaml
