apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: helmrepo
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./ncm-app/helmcharts/helmrepo-1.0.4.tgz  
      version: '1.0.4'
      sourceRef:
        kind: GitRepository
        name: ncm-app # kpt-set: ${gitreponame}
        namespace: default
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: profop # kpt-set: ${targetNamespace}
  valuesFrom:
  - kind: ConfigMap
    name: helmrepo-values
    valuesKey: values.yaml
