apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ncm-app
  namespace: default
spec:
  kubeConfig:
    secretRef:
      name: target-kubeconfig # kpt-set: ${targetKubeconfig}
  interval: 1m
  chart:
    spec:
      chart: ./ncm-app/helmcharts/ncm-app-2.3.2.tgz  
      version: '2.3.2'
      sourceRef:
        kind: GitRepository
        name: ncm-app # kpt-set: ${gitreponame}
        namespace: default
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: network-function-flux-a # kpt-set: ${targetNamespace}
  valuesFrom:
  - kind: ConfigMap
    name: ncm-app-values
    valuesKey: values.yaml
