apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ncm-app
  namespace: default
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: ncm-app
      version: '2.3.2'
      sourceRef:
        kind: HelmRepository
        name: helmrepo
      interval: 5m
  releaseName: ncm-app
  targetNamespace: default 
  valuesFrom:
  - kind: ConfigMap
    name: ncm-app-values
    valuesKey: values.yaml
